#!/usr/bin/env bash
# generated by `quipu setup` — PostToolUse (Edit|Write) hook: completion-debt
# + header-drift reporting. When a doc under docs/rfc/ is edited, refresh
# the hub and inject that doc's parsed state back into the session at the
# moment it can be acted on.
set -u
payload=$(cat)
fp=$(jq -r '.tool_input.file_path // ""' <<<"$payload")
case "$fp" in
  */docs/rfc/[0-9][0-9][0-9][0-9]-*.md) ;;
  *) exit 0 ;;
esac
base=$(basename "$fp")
num=${base%%-*}
txt=$(jq -r '(.tool_input.new_string // "") + (.tool_input.content // "")' <<<"$payload")

mode=""
case "$base" in
  *.handoff.md)
    grep -qiE 'floor|review|round' <<<"$txt" && mode="handoff" ;;
  *.*.md)
    ;;  # other companion docs carry neither Status nor the review ledger
  *)
    if grep -qi 'status' <<<"$txt" && grep -qi 'implemented' <<<"$txt"; then
      mode="status"
    fi ;;
esac
[ -n "$mode" ] || exit 0

curl -sf -X POST --max-time 10 https://quipu.leavitt.dev/p/nelli/sync -o /dev/null 2>/dev/null || exit 0
node=$(curl -sf --max-time 10 https://quipu.leavitt.dev/p/nelli/api/graph 2>/dev/null \
        | jq -c --arg n "$num" '.nodes[] | select(.id==$n)') || exit 0
[ -n "$node" ] || exit 0

has_debt=$(jq -r '.has_debt' <<<"$node")
review=$(jq -r '.review_state' <<<"$node")
open=$(jq -r '.open_count' <<<"$node")
drift=$(jq -r 'if (.review_drift_dismissed // false) then "" else (.review_drift // "") end' <<<"$node")

msgs=()
if [ -n "$drift" ]; then
  msgs+=("quipu: RFC-$num $drift — if this session's review reached the floor, update the doc's Status line to say so now; if the floor evidence covers a different scope, leave the header and say so.")
fi
if [ "$mode" = "status" ] && [ "$has_debt" = "true" ]; then
  msgs+=("quipu: RFC-$num is complete-with-debt — review_state=$review, open_items=$open. If deliberate, fine; otherwise state the review outcome in the Status line and mark resolved leftover bullets with a resolution marker (✅ / RESOLVED / ~~strike~~ / [x]).")
  if [ "$open" -gt 0 ] 2>/dev/null; then
    items=$(curl -sf --max-time 10 "https://quipu.leavitt.dev/p/nelli/api/rfc/$num" 2>/dev/null \
      | jq -r '.open_items[:3][] | "  - [" + (.section // "" | .[0:40]) + "] " + (.text | .[0:120]) + " (" + .source_path + ":" + (.line|tostring) + ")"') \
      && [ -n "$items" ] && msgs+=("Top open items:
$items")
  fi
fi
if [ ${#msgs[@]} -gt 0 ]; then
  m=$(printf '%s\n' "${msgs[@]}")
  jq -n --arg m "$m" \
    '{systemMessage:$m, hookSpecificOutput:{hookEventName:"PostToolUse", additionalContext:$m}}'
fi
exit 0
