# Package

version       = "0.5.1"
author        = "Corey Leavitt"
description   = "Property-based testing for Nim with internal choice-sequence shrinking (a Hypothesis-style engine)"
license       = "Apache-2.0"
srcDir        = "src"

# Dependencies

requires "nim >= 2.0.0"

# Tasks

task test, "Run the test suite":
  for f in ["tsmoke", "tchoice", "tserialize", "trng", "tdatasource",
            "tstrategy", "tstrategies", "tengine", "tshrinker", "tdsl",
            "tderive", "tdb", "tstateful", "ttarget", "tbias",
            "tdisplay", "tdeadline", "tevents", "texamples", "tbundles",
            "texplain", "tnested", "twiderange", "tdbbackends", "treporter",
            "tfuzzbytes", "tcoverage", "tcoveragemode",
            "tcovguided", "treservedlabel", "tfuzzir", "tfuzzcbuild", "tfuzzcovdump",
            "tfuzzfrontier", "tfuzzprobe", "tfuzzloop", "tfuzzexec", "tfuzzexternal", "tfuzzdiff", "tfuzzdedup", "tfuzzpersist", "tfuzzcovcorpus", "tfuzzprimarymeta", "tfuzzmincover", "tfuzzschedule", "tfuzzseedcov", "tfuzzinterop", "tfuzzpackaging", "tfuzzstopcrash", "tfuzzdroppedseed", "tfuzzsectionsize", "tautolabels",
            "tsymbolic", "tdetect", "trefine", "tdistribution",
            "tbiasthreading", "tfuzzbias", "tshrinkpass", "tbmc",
            "tmining", "tbisim", "tmutation",
            "tlinearisable", "tjsonschema",
            "tlaws", "tmetamorphic", "tparallelcheck", "tpipeline",
            "trequiresinit", "tcombine", "tfrequency",
            "tsymex_phase1_arith", "tsymex_phase1_bool",
            "tsymex_phase1_let", "tsymex_phase1_assert",
            "tsymex_phase1_dsl",
            "tsymex_phase2_bv_arith", "tsymex_phase2_abstraction",
            "tsymex_phase2_fallback", "tsymex_phase2_overflow",
            "tsymex_phase3_inline", "tsymex_phase3_recursion",
            "tsymex_phase3_summarization", "tsymex_phase3_mutual",
            "tsymex_phase3_stdlib",
            "tsymex_phase4_tuple", "tsymex_phase4_nested",
            "tsymex_phase4_array", "tsymex_phase4_oob",
            "tsymex_phase5_seq", "tsymex_phase5_table",
            "tsymex_phase5_hashset", "tsymex_phase5_models",
            "tsymex_rectify_effects", "tsymex_rectify_cardinality",
            "tsymex_rectify_mutation", "tsymex_rectify_nested_arrays",
            "tsymex_rectify_variants", "tsymex_rectify_abstraction",
            "tsymex_rectify_generics", "tsymex_rectify_refs",
            "tsymex_phase6_while", "tsymex_phase6_for",
            "tsymex_phase6_case", "tsymex_phase6_break",
            "tsymex_phase7_assertcovered",
            "tsymex_canonicalize",
            "tsymex_typebridge_variants",
            "tsymex_phase11_walker",
            "tsymex_phase11_fielddefect",
            "tsymex_phase14_multivariant_ir",
            "tsymex_phase14_multivariant_typebridge",
            "tsymex_phase14_multivariant_walker",
            "tsymex_phase14_multivariant_witness",
            "tsymex_phase14_else_arms",
            "tsymex_phase14_nonenum_disc",
            "tsymex_phase14_symbolic_disc_reassign",
            "tsymex_phase14_arm_field_zero_init",
            "tsymex_phase14_disc_promotion",
            "tsymex_phase14_var_param",
            "tsymex_phase14_var_param_downstream",
            "tsymex_phase14_strategy_digest",
            "tsymex_phase14_b2_forcephases",
            "tsymex_phase14_b3_trace_equivalence",
            "tsymex_phase14_b5_replaymiss",
            "tsymex_phase14_b67_label_filter",
            "tsymex_phase14_c1_fromcache",
            "tsymex_phase14_c2_dberrors",
            "tsymex_phase14_frontier_pruning",
            "tsymex_phase14_c4_z3error",
            "tsymex_phase15_z0_carryover",
            "tsymex_phase15_z1_canary",
            "tsymex_phase15_z3_infra",
            "tsymex_phase15_z3c_classify",
            "tsymex_phase15_z4_walkctx",
            "tsymex_phase15_CR2_cachekey",
            "tsymex_phase15_l1_boundary",
            "tsymex_phase15_l2_untyped_template",
            "tsymex_phase15_l3_quote_do",
            "tsymex_phase15_F1_typebridge",
            "tsymex_phase15_F2_float_literals",
            "tsymex_phase15_F3_float_arith",
            "tsymex_phase15_F4_float_compare",
            "tsymex_phase15_F5_float_conv",
            "tsymex_phase15_F6_float_math",
            "tsymex_phase15_F7_float_extract",
            "tsymex_phase15_F8_smoke",
            "tsymex_phase15_F9a_array_float",
            "tsymex_phase15_F9b_seq_float",
            "tsymex_phase15_F9c_variant_float",
            "tsymex_phase15_S1_typebridge",
            "tsymex_phase15_S2_strlit",
            "tsymex_phase15_S3_strindex",
            "tsymex_phase15_S4_strpred",
            "tsymex_phase15_S5_strops",
            "tsymex_phase15_S6a_regex_parser",
            "tsymex_phase15_S6b_regex",
            "tsymex_phase15_S7a_bytes",
            "tsymex_phase15_S7b_smoke",
            "tsymex_phase15_S8_concat",
            "tsymex_phase15_S9_caseconv",
            "tsymex_phase15_S10a_strconv",
            "tsymex_phase15_S10b_strconv",
            "tsymex_phase15_S11_mutation",
            "tsymex_phase15_H1_path_heap_fields",
            "tsymex_phase15_E1_ir",
            "tsymex_phase15_E2a_cascade",
            "tsymex_phase15_E2b_raise",
            "tsymex_phase15_E3_try",
            "tsymex_phase15_E4_hierarchy",
            "tsymex_phase15_E4a_userexn",
            "tsymex_phase15_E5_finally",
            "tsymex_phase15_E6_defect",
            "tsymex_phase15_E7_smoke",
            "tsymex_phase15_E8_getcurrentexn",
            "tsymex_phase15_G1a_instkey",
            "tsymex_phase15_G1c_instcap",
            "tsymex_phase15_g3_type_subst",
            "tsymex_phase15_g4_distinct_sort",
            "tsymex_phase15_g5_distinct_borrow",
            "tsymex_phase15_g6_concept_constraint",
            "tsymex_phase15_g7_static_param",
            "tsymex_phase15_g8_multi_param",
            "tsymex_phase15_g10_smoke",
            "tsymex_phase15_C1_ir",
            "tsymex_phase15_C2a_closure_capture",
            "tsymex_phase15_C2b_closure_call",
            "tsymex_phase15_C3_proc_as_value",
            "tsymex_phase15_C4_hof",
            "tsymex_phase15_C5_closure_eq",
            "tsymex_phase15_C6_smoke",
            "tsymex_phase15_R1a_ir",
            "tsymex_phase15_r1_refsort",
            "tsymex_phase15_r1b_callheap",
            "tsymex_phase15_r2_new",
            "tsymex_phase15_r3_deref_read",
            "tsymex_phase15_r4_deref_write",
            "tsymex_phase15_r5_nil",
            "tsymex_phase15_r6_refobj",
            "tsymex_phase15_r7_alias_chain",
            "tsymex_phase15_r8_ptr",
            "tsymex_phase15_r8b_varref",
            "tsymex_phase15_r9_recursive",
            "tsymex_phase15_r10_budget",
            "tsymex_phase15_r11_unsafecast",
            "tsymex_phase15_r11b_smoke",
            "tsymex_phase15_r12_bumps",
            "tsymex_phase15_r13_closure_ref",
            "tsymex_phase15_r13_ptr_finally",
            "tsymex_retest_c3_bitwise_guard",
            "tsymex_retest_c5b_unknown_errors",
            "tsymex_retest_c6_tuple_chain",
            "tsymex_retest_c11_stack",
            "tsymex_retest_pred_succ",
            "tsymex_retest_defect_net",
            "tsymex_retest_infix_degrade",
            "tsymex_retest_char_needle",
            "tsymex_r4_slice_binding",
            "tsymex_r4_strip",
            "tsymex_r4_seq_slice",
            "tsymex_r5_discard",
            "tsymex_r5_bv32_width",
            "tsymex_r5_tuple_return",
            "tsymex_r5_neg_bool_conv",
            "tsymex_r5_const_fold",
            "tsymex_r6_b0_scanlift_bound",
            "tsymex_r6_a0_lowhigh",
            "tsymex_r6_a1_variantlit",
            "tsymex_r6_a2_retbind_variant",
            "tsymex_r6_a3_variantconstruct_sym",
            "tsymex_r6_a4_construct_interactions",
            "tsymex_r6_a6_exported_field_names",
            "tsymex_r6_b1_stringbacked",
            "tsymex_r6_b2_intwidth",
            "tsymex_r6_b3_scanpair",
            "tsymex_r6_b4_readcstring",
            "tsymex_r6_b5_chained",
            "tsymex_r6_b6_optionregion",
            "tsymex_r6_nulwitness",
            "tsymex_r6_bug2_scopeddecline",
            "tsymex_r6_a6r_callwitness",
            "tsymex_r6_b7r_bytescan",
            "tsymex_r6_b7r2_pathscope",
            "tsymex_r6_r1_placeholder_totality",
            "tsymex_r6_r2_zerodefault_result",
            "tsymex_r6_r3_svint_overflow",
            "tsymex_r6_r4_collector_scoping",
            "tsymex_r6_r5_pairloop_counter",
            "tsymex_r6_n9_variant_budget",
            "tsymex_r6_n10_coverage_matrix",
            "tsymex_r6_r6_emit_roundtrip",
            "tsymex_r6_n21_pairloop_member",
            "tsymex_r6_n16_closure_zerodefault",
            "tsymex_r6_n27_hof_placeholder",
            "tsymex_r6_n27_placeholder_read_audit",
            "tsymex_r6_n28_shadow_collision",
            "tsymex_r6_n13_reassign_seqarm",
            "tsymex_r6_d2_recursive_budget",
            "tsymex_r6_n31_block_counter",
            "tsymex_r6_n36_raise_degrade",
            "tsymex_r6_n36_raise_class_audit",
            "tsymex_r6_n37_raise_residue",
            "tsymex_r6_n39_variant_field_alloc",
            "tsymex_r6_n40_alloc_totality",
            "tsymex_r6_n42_deref_taint",
            "tsymex_r6_lows_collectors",
            "tsymex_r6_lows_blockparse",
            "tsymex_r6_lows_declines",
            "tsymex_funcdef_callee",
            "tsymex_phase15_N0_kindgate_widen",
            "tsymex_phase15_N1_resolution_gates",
            "tsymex_phase15_N2_kindgate_audit",
            "tsymex_phase15_N3_scan_boundary",
            "tsymex_phase15_C2_staticparams",
            "tsymex_phase15_A1_bitwise",
            "tsymex_phase15_A1_comparison",
            "tsymex_phase15_A1_arithmetic",
            "tsymex_phase15_A1_boolean",
            "tsymex_phase15_A1_loopguard",
            "tsymex_phase15_A1_unary",
            "tsymex_phase15_A1_callarg",
            "tsymex_phase15_A1_assertarg",
            "tsymex_phase15_A2a_chokepoint_audit",
            "tsymex_phase15_A2a_atomicir_audit",
            "tsymex_phase15_A2a_atomize",
            "tsymex_phase15_A2a_guardcond_pin",
            "tsymex_phase15_A2b_bitwise",
            "tsymex_phase15_C1_canonical_kind",
            "tsymex_q1_sibling_collision",
            "tcovsourcetable"]:
    exec "nim c -r --threads:on --hints:off --path:src tests/" & f & ".nim"
