## RFC-0005 S8bt (item 5) -- UTF mode's Unicode semantics from PCRE 8.45's
## own tables (`pcre_ucd.nim`, generated by `scripts/gen-pcre-ucd.py`):
## `\p{..}` / `\P{..}`, `(*UCP)`'s `\d \s \w` and POSIX classes, and
## Unicode case folding (OP_CHARI's other case, PT_CLIST's caseless sets,
## a caseless class range's `add_to_class`), against the libpcre std/re
## loads; then whole patterns, concretely (`pcreExec`, `pcreReplace`)
## against std/re on UTF-8 subjects.
import std/[unittest, strutils, re, times, sets, algorithm]
import nelli/smt/[pcre_syntax, pcre_select, pcre_ucd, pcre_engine]

var t0 = epochTime()
proc lap(): string =
  let t = epochTime()
  result = formatFloat(t - t0, ffDecimal, 1) & " s"
  t0 = t

proc enc(c: int32): string = utf8Encode(c)

proc valid(c: int32): bool = c >= 0 and c <= maxCp and (c < 0xD800 or c > 0xDFFF)

proc atomSet(p: string): CpSet =
  ## The code points of a one-character pattern, as the reader reads them.
  let r = parsePcre(p)
  doAssert r.status == psOk, p & ": " & $r.status & " " & r.reason
  var x = r.root
  while x.kind == rxCat and x.kids.len == 1: x = x.kids[0]
  doAssert x.kind == rxChars, p & ": " & $x.kind
  x.cps

proc pcreHas(rx: Regex; c: int32): bool =
  let s = enc(c)
  s.matchLen(rx) == s.len

proc probes(cs: CpSet; extra: openArray[int32] = []): seq[int32] =
  ## Each range's edges and their neighbours, a sample inside, and `extra`.
  var hs: HashSet[int32]
  for (lo, hi) in cs:
    for c in [lo - 1, lo, lo + 1, (lo + hi) div 2, hi - 1, hi, hi + 1]:
      if valid(c): hs.incl c
  for c in extra:
    if valid(c): hs.incl c
  result = hs.toSeq
  result.sort()

var sample: seq[int32]
block:
  var c = 0'i32
  while c <= maxCp:
    if valid(c): sample.add c
    c += (if c < 0x3000: 7 else: 997)

proc checkSet(p: string; extra: openArray[int32]; bad: var seq[string]):
    int =
  let m = atomSet(p)
  let rx = re(p)
  for c in probes(m, extra):
    inc result
    if pcreHas(rx, c) != cpHas(m, c):
      bad.add escape(p) & " U+" & toHex(c, 4) & ": pcre " & $pcreHas(rx, c)
      if bad.len > 40: return

suite "S8bt: UTF mode's Unicode tables against libpcre":

  test "every property (\\p and \\P)":
    var bad: seq[string]
    var n = 0
    for (name, _) in ucdProps:
      if name.startsWith("["): continue
      n += checkSet("(*UTF8)\\p{" & name & "}", sample, bad)
      n += checkSet("(*UTF8)\\P{" & name & "}", [], bad)
      n += checkSet("(*UTF8)\\p{^" & name & "}", [], bad)
    echo "  ", ucdProps.len - 3, " properties, ", n, " code points, ",
         bad.len, " differ, ", lap()
    checkpoint bad.join("\n")
    check bad.len == 0

  test "(*UCP): \\d \\s \\w and the POSIX classes":
    var bad: seq[string]
    var n = 0
    for e in ["\\d", "\\D", "\\s", "\\S", "\\w", "\\W"]:
      n += checkSet("(*UTF8)(*UCP)" & e, sample, bad)
      n += checkSet("(*UTF8)(*UCP)[" & e & "]", [], bad)
    for name in ["alpha", "lower", "upper", "alnum", "ascii", "blank",
                 "cntrl", "digit", "graph", "print", "punct", "space",
                 "word", "xdigit"]:
      for neg in ["", "^"]:
        n += checkSet("(*UTF8)(*UCP)[[:" & neg & name & ":]]", sample, bad)
        n += checkSet("(*UTF8)(*UCP)[[:" & neg & name & ":]\\x{2028}]", [],
                      bad)
        n += checkSet("(*UTF8)(*UCP)[^[:" & neg & name & ":]]", [], bad)
    # Mixed with properties, ranges and negation.
    for p in ["(*UTF8)[\\p{Lu}a-c]", "(*UTF8)[^\\p{L}\\d]",
              "(*UTF8)(*UCP)[\\w\\x{2000}-\\x{200f}]", "(*UTF8)[\\P{Greek}]",
              "(*UTF8)(*UCP)[^\\s\\p{N}]", "(*UTF8)(?i)[\\p{Ll}]"]:
      n += checkSet(p, sample, bad)
    echo "  ", n, " code points, ", bad.len, " differ, ", lap()
    checkpoint bad.join("\n")
    check bad.len == 0

  test "case folding: each character, caseless":
    var bad: seq[string]
    var n = 0
    var cased: seq[int32]
    for (lo, hi, d) in ucdOtherCase:
      for c in lo .. hi:
        cased.add c
    for st in ucdCaseSets:
      for c in st: cased.add c
    for c in cased:
      var near: seq[int32]
      for d in [-2'i32, -1, 1, 2, 32, -32]: near.add c + d
      near.add ucdOther(c)
      near.add ucdOther(ucdOther(c))
      if c < 0x600:
        for x in 0'i32 ..< 0x600: near.add x
      n += checkSet("(*UTF8)(?i)" & enc(c), near, bad)
      n += checkSet("(*UTF8)(?i)[" & enc(c) & "]", near, bad)
      n += checkSet("(*UTF8)(?i)[^" & enc(c) & "]", near, bad)
      if bad.len > 40: break
    echo "  ", cased.len, " characters, ", n, " code points, ", bad.len,
         " differ, ", lap()
    checkpoint bad.join("\n")
    check bad.len == 0

  test "case folding: caseless class ranges":
    var bad: seq[string]
    var n = 0
    var ranges: seq[(int32, int32)]
    # Ranges that start, end and extend on runs of other cases, through
    # characters with caseless sets, and across scripts.
    for (lo, hi, d) in ucdOtherCase[0 .. min(ucdOtherCase.high, 400)]:
      ranges.add (lo, hi)
      ranges.add (max(lo - 3, 0), lo + 1)
      ranges.add (hi - 1, hi + 5)
    for x in [(0x41'i32, 0x5A'i32), (0x61'i32, 0x7A'i32), (0x6A'i32, 0x6C'i32),
              (0x72'i32, 0x74'i32), (0xC0'i32, 0xFF'i32), (0x100'i32, 0x17F'i32),
              (0x370'i32, 0x3FF'i32), (0x391'i32, 0x3A9'i32), (0x2100'i32, 0x2140'i32),
              (0x1E00'i32, 0x1EFF'i32), (0x10400'i32, 0x1044F'i32),
              (0x1F0'i32, 0x1F5'i32), (0x0'i32, 0x10FFFF'i32)]:
      ranges.add x
    for (lo, hi) in ranges:
      if not valid(lo) or not valid(hi) or lo > hi: continue
      let p = "(*UTF8)(?i)[" & enc(lo) & "-" & enc(hi) & "]"
      var near: seq[int32]
      for c in max(lo - 64, 0) .. min(hi + 64, maxCp):
        if hi - lo < 4000: near.add c
      n += checkSet(p, near & sample, bad)
      if bad.len > 40: break
    echo "  ", ranges.len, " ranges, ", n, " code points, ", bad.len,
         " differ, ", lap()
    checkpoint bad.join("\n")
    check bad.len == 0

const
  utfPats* = [
    "(*UTF8)\\p{L}+", "(*UTF8)\\P{Lu}\\p{Ll}?", "(*UTF8)(*UCP)\\w+",
    "(*UTF8)(*UCP)\\d|\\s", "(*UTF8)(*UCP)[[:alpha:]]+b",
    "(*UTF8)(*UCP)[^[:punct:]]", "(*UTF8)(?i)k", "(*UTF8)(?i)k+",
    "(*UTF8)(?i)[r-t]+", "(*UTF8)(?i)\\x{3a3}", "(*UTF8)(?i)[\\x{3c3}a]",
    "(*UTF8)(?i)é", "(*UTF8)(?i)é+a", "(*UTF8)\\p{Greek}\\p{Latin}?",
    "(*UTF8)(?i)[^k]", "(*UTF8)(?i)[^é]+", "(*UTF8)(?i)ks|é",
    "(*UTF8)(?i)(?:\\x{3c2}|a)b", "(*UTF8)(?i)k(*SKIP)a|.",
    "(*UTF8)(*UCP)\\S\\W", "(*UTF8)(?i)\\x{212a}*a", "(*UTF8)(?i)[k-s]a",
    "(*UTF8)(?i)ab", "(*UTF8)(?i)[a-z]{2}", "(*UTF8)(?i)ß|\\x{1e9e}",
    "(*UTF8)(?i)\\x{1c5}"]
  utfAlpha* = ["a", "k", "K", "K", "s", "ſ", "é", "É",
               "Σ", "σ", "ς", "٣", "　", "_", "1",
               "!", "ß", "Ǆ"]

proc utfWords(): seq[string] =
  result = @[""]
  for a in utfAlpha:
    result.add a
    for b in utfAlpha: result.add a & b

suite "S8bt: UTF patterns, concretely, against std/re":

  test "find, last and replace at every start":
    var bad: seq[string]
    var calls = 0
    for p in utfPats:
      let pr = parsePcre(p)
      check pr.status == psOk
      if pr.status != psOk:
        bad.add escape(p) & ": " & pr.reason
        continue
      let n = buildNfa(pr, pcreSearchEngine())
      check n.ok
      if not n.ok:
        bad.add escape(p) & ": " & n.why
        continue
      let rx = re(p)
      for s in utfWords():
        var st = 0
        while st <= s.len:
          inc calls
          let want = (find(s, rx, st), findBounds(s, rx, st).last)
          let (rc, a, b) = pcreExec(n, s, st, false)
          let got = (if rc == 1: (a, b - 1) elif rc == -1: (-1, 0)
                     else: (rc, 0))
          if got != want and bad.len < 40:
            bad.add escape(p) & " find/last(" & escape(s) & ", " & $st &
                    ") = " & $got & ", std/re: " & $want
          let ml = s.matchLen(rx, st)
          let (rc2, _, b2) = pcreExec(n, s, st, true)
          let gotMl = (if rc2 == 1: b2 - st else: rc2)
          if gotMl != ml and bad.len < 40:
            bad.add escape(p) & " matchLen(" & escape(s) & ", " & $st &
                    ") = " & $gotMl & ", std/re: " & $ml
          inc st
        let want = replace(s, rx, "-")
        if pcreReplace(n, s, "-") != want and bad.len < 40:
          bad.add escape(p) & " replace(" & escape(s) & ")"
    echo "  ", utfPats.len, " patterns, ", calls, " calls, ", bad.len,
         " differ, ", lap()
    checkpoint bad.join("\n")
    check bad.len == 0
